/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 black-jac-remastered.glb --transform
Files: black-jac-remastered.glb [44.97MB] > /home/thrill/Downloads/black-jac-remastered-transformed.glb [2MB] (96%)
*/

import { useGLTF } from "@react-three/drei";

const BlackJacRemastered = (props) => {
  const { nodes, materials } = useGLTF(
    "models/black-jac-remastered-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[-0.005, 0.014, -0.563]}
        rotation={[-1.611, 0, 0]}
        scale={[-0.101, -0.127, -0.033]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.002"]}
        position={[0, -0.01, 0.555]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.095, 0.145, 0.04]}
      />
    </group>
  );
};

export default BlackJacRemastered;

useGLTF.preload("models/black-jac-remastered-transformed.glb");
