/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 red-jac-remastered.glb --transform
Files: red-jac-remastered.glb [47.73MB] > /home/thrill/Downloads/red-jac-remastered-transformed.glb [2.07MB] (96%)
*/

import { useGLTF } from "@react-three/drei";

const RedJacRemastered = (props) => {
  const { nodes, materials } = useGLTF(
    "models/red-jac-remastered-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.002"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.002"]}
        position={[0, 0.04, 0.549]}
        rotation={[0.683, 0, 0]}
        scale={[0.025, 0.023, 0.01]}
      />
    </group>
  );
};

useGLTF.preload("models/red-jac-remastered-transformed.glb");
export default RedJacRemastered;
