/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 red-suv.glb --transform
Files: red-suv.glb [47.73MB] > /home/thrill/Downloads/red-suv-transformed.glb [2.07MB] (96%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const RedSUV = (props) => {
  const { nodes, materials } = useGLTF("models/red-suv-2-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.002"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.003"]}
        position={[0, 0.037, 0.549]}
        rotation={[0.683, 0, 0]}
        scale={[0.025, 0.019, 0.009]}
      />
    </group>
  );
};

useGLTF.preload("models/red-suv-2-transformed.glb");
export default RedSUV;
