/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 44ca5a163dfa6756236695290e238dfb.glb --transform
Files: 44ca5a163dfa6756236695290e238dfb.glb [84.73MB] > /home/thrill/Downloads/jac-red/jac red car/44ca5a163dfa6756236695290e238dfb-transformed.glb [4.59MB] (95%)
*/

import { useGSAP } from "@gsap/react";
import { useGLTF } from "@react-three/drei";
import { useGraph, useThree } from "@react-three/fiber";
import gsap from "gsap";
import { useMemo, useRef } from "react";
import { useMediaQuery } from "react-responsive";
import { SkeletonUtils } from "three-stdlib";

const WhiteJac = (props) => {
  const groupRef = useRef();
  const { camera } = useThree();
  const { scene } = useGLTF("models/jac-white.glb");
  const clone = useMemo(() => {
    return SkeletonUtils.clone(scene);
  }, [scene]);

  const { nodes, materials } = useGraph(clone);
  const isSmall = useMediaQuery({
    maxWidth: 440,
  });

  const defaultPos = isSmall ? [0, -2, 0] : [0, -1.5, 0];

  useGSAP(() => {
    if (!groupRef.current) return;

    gsap.set(camera.position, {
      x: 0,
      y: 0,
      z: 27,
    });

    gsap.set(groupRef.current.position, {
      x: -30,
      y: defaultPos[1],
      z: defaultPos[2],
    });

    gsap.set(groupRef.current.rotation, {
      x: 0,
      y: Math.PI / 2,
      z: 0,
    });

    gsap.to(groupRef.current.position, {
      x: defaultPos[0],
      duration: 2.5,
      delay: 0.6,
      ease: "power3.out",
    });

    gsap.to(groupRef.current.rotation, {
      y: Math.PI / 1.9,
      duration: 2,
      delay: 0.4,
      ease: "power3.out",
    });
  }, [props.animationKey]);

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      ></mesh>
    </group>
  );
};

useGLTF.preload("models/jac-white.glb");
export default WhiteJac;
