/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 white-suv.glb --transform
Files: white-suv.glb [47.57MB] > /home/thrill/Downloads/white-suv-transformed.glb [1.98MB] (96%)
*/

import { useGLTF } from "@react-three/drei";

const WhiteSuv = (props) => {
  const { nodes, materials } = useGLTF("models/white-suv-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.material.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("models/white-suv-transformed.glb");
export default WhiteSuv;
